-- -- Clear existing data in correct order
-- DELETE FROM meal_plan;
-- DELETE FROM recipe_ingredient;
-- DELETE FROM pantry;
-- DELETE FROM shopping_list;
-- DELETE FROM recipe;
-- DELETE FROM ingredient;
-- DELETE FROM ingredient_category;
-- DELETE FROM kitchen;
--
-- -- Insert ingredient categories
-- INSERT INTO ingredient_category (id, name)
-- VALUES
--     (gen_random_uuid(), 'Vegetables'),
--     (gen_random_uuid(), 'Fruits'),
--     (gen_random_uuid(), 'Meats'),
--     (gen_random_uuid(), 'Dairy'),
--     (gen_random_uuid(), 'Grains'),
--     (gen_random_uuid(), 'Spices'),
--     (gen_random_uuid(), 'Herbs'),
--     (gen_random_uuid(), 'Pantry Staples');
--
-- -- Insert real ingredients
-- INSERT INTO ingredient (id, name, ingredient_category_id)
-- SELECT gen_random_uuid(), ingredients.name, cat.id
-- FROM (
--          VALUES
--              -- Vegetables
--              ('Carrot', 'Vegetables'),
--              ('Onion', 'Vegetables'),
--              ('Garlic', 'Vegetables'),
--              ('Bell Pepper', 'Vegetables'),
--              ('Tomato', 'Vegetables'),
--              ('Potato', 'Vegetables'),
--              ('Broccoli', 'Vegetables'),
--              ('Spinach', 'Vegetables'),
--              ('Mushroom', 'Vegetables'),
--              ('Zucchini', 'Vegetables'),
--              -- Fruits
--              ('Lemon', 'Fruits'),
--              ('Lime', 'Fruits'),
--              ('Apple', 'Fruits'),
--              ('Orange', 'Fruits'),
--              -- Meats
--              ('Chicken Breast', 'Meats'),
--              ('Ground Beef', 'Meats'),
--              ('Bacon', 'Meats'),
--              ('Salmon', 'Meats'),
--              ('Pork Chop', 'Meats'),
--              -- Dairy
--              ('Butter', 'Dairy'),
--              ('Milk', 'Dairy'),
--              ('Heavy Cream', 'Dairy'),
--              ('Parmesan Cheese', 'Dairy'),
--              ('Mozzarella', 'Dairy'),
--              -- Grains
--              ('Rice', 'Grains'),
--              ('Pasta', 'Grains'),
--              ('Bread Crumbs', 'Grains'),
--              ('Flour', 'Grains'),
--              -- Spices
--              ('Salt', 'Spices'),
--              ('Black Pepper', 'Spices'),
--              ('Paprika', 'Spices'),
--              ('Cumin', 'Spices'),
--              ('Cayenne Pepper', 'Spices'),
--              -- Herbs
--              ('Basil', 'Herbs'),
--              ('Thyme', 'Herbs'),
--              ('Rosemary', 'Herbs'),
--              ('Parsley', 'Herbs'),
--              -- Pantry Staples
--              ('Olive Oil', 'Pantry Staples'),
--              ('Soy Sauce', 'Pantry Staples'),
--              ('Honey', 'Pantry Staples'),
--              ('Vinegar', 'Pantry Staples')
--      ) AS ingredients(name, category_name)
--          JOIN ingredient_category cat ON cat.name = ingredients.category_name;
--
-- -- Insert kitchens
-- INSERT INTO kitchen (id, name)
-- VALUES
--     (gen_random_uuid(), 'Italian'),
--     (gen_random_uuid(), 'American'),
--     (gen_random_uuid(), 'Asian'),
--     (gen_random_uuid(), 'Mediterranean');
--
-- -- Insert actual recipes
-- WITH recipe_data(name, description, kitchen_name) AS (
--     VALUES
--         -- Italian Kitchen
--         ('Classic Spaghetti Carbonara', 'Creamy pasta dish with bacon and parmesan', 'Italian'),
--         ('Chicken Parmesan', 'Breaded chicken with tomato sauce and mozzarella', 'Italian'),
--         ('Margherita Pizza', 'Traditional pizza with tomatoes, mozzarella, and basil', 'Italian'),
--         -- American Kitchen
--         ('Homemade Burger', 'Juicy beef burger with fresh vegetables', 'American'),
--         ('BBQ Chicken', 'Grilled chicken with homemade BBQ sauce', 'American'),
--         ('Mac and Cheese', 'Creamy macaroni and cheese', 'American'),
--         -- Asian Kitchen
--         ('Stir-Fried Rice', 'Classic fried rice with vegetables', 'Asian'),
--         ('Teriyaki Salmon', 'Salmon glazed with teriyaki sauce', 'Asian'),
--         ('Chicken Curry', 'Spicy chicken curry with vegetables', 'Asian'),
--         -- Mediterranean Kitchen
--         ('Greek Salad', 'Fresh vegetables with olive oil and herbs', 'Mediterranean'),
--         ('Grilled Vegetables', 'Mediterranean style grilled vegetables', 'Mediterranean'),
--         ('Herb Roasted Chicken', 'Chicken roasted with Mediterranean herbs', 'Mediterranean')
-- )
-- INSERT INTO recipe (id, name, description, kitchen_id, user_id, is_public, preparation_time)
-- SELECT
--     gen_random_uuid(),
--     r.name,
--     r.description,
--     k.id,
--     '2f79a780-f729-4088-bf99-0331386e7678',
--     true,
--     (random() * 60 + 30)::int
-- FROM recipe_data r
--          JOIN kitchen k ON k.name = r.kitchen_name;
--
-- -- Insert recipe ingredients with actual quantities
-- WITH recipe_ingredients(recipe_name, ingredient_name) AS (
--     VALUES
--         -- Carbonara ingredients
--         ('Classic Spaghetti Carbonara', 'Pasta'),
--         ('Classic Spaghetti Carbonara', 'Bacon'),
--         ('Classic Spaghetti Carbonara', 'Parmesan Cheese'),
--         ('Classic Spaghetti Carbonara', 'Black Pepper'),
--         -- Burger ingredients
--         ('Homemade Burger', 'Ground Beef'),
--         ('Homemade Burger', 'Onion'),
--         ('Homemade Burger', 'Salt'),
--         ('Homemade Burger', 'Black Pepper')
--     -- Add more recipe ingredients as needed
-- )
-- INSERT INTO recipe_ingredient (ingredient_id, recipe_id)
-- SELECT i.id, r.id
-- FROM recipe_ingredients ri
--          JOIN ingredient i ON i.name = ri.ingredient_name
--          JOIN recipe r ON r.name = ri.recipe_name;
--
-- -- Insert meal plans with exactly 2 meals per day
-- WITH meal_times AS (
--     SELECT
--         r.id as recipe_id,
--         date_time
--     FROM (
--              SELECT id FROM recipe ORDER BY random() LIMIT 14 -- 2 meals × 7 days
--          ) r
--              CROSS JOIN (
--         SELECT current_date + (d || ' days')::interval +
--             CASE WHEN h = 0 THEN '12:00'::interval  -- Lunch at 12:00
--                  ELSE '18:00'::interval  -- Dinner at 18:00
--             END as date_time
--         FROM generate_series(0, 6) d
--             CROSS JOIN generate_series(0, 1) h -- Generate 2 times per day
--     ) dates
-- )
-- INSERT INTO meal_plan (id, recipe_id, start_date, end_date, user_id)
-- SELECT
--     gen_random_uuid(),
--     recipe_id,
--     date_time,
--     date_time + interval '1 hour',
--     '2f79a780-f729-4088-bf99-0331386e7678'
-- FROM meal_times;
--
-- -- Insert pantry items
-- INSERT INTO pantry (id, ingredient_id, user_id)
-- SELECT
--     gen_random_uuid(),
--     id,
--     '2f79a780-f729-4088-bf99-0331386e7678'
-- FROM (
--          SELECT id FROM ingredient
--          WHERE name IN (
--                         'Salt', 'Black Pepper', 'Olive Oil', 'Pasta',
--                         'Rice', 'Flour', 'Soy Sauce', 'Honey'
--              )
--      ) as staples;
--
-- -- Insert shopping list
-- INSERT INTO shopping_list (id, ingredient_id, user_id)
-- SELECT
--     gen_random_uuid(),
--     id,
--     '2f79a780-f729-4088-bf99-0331386e7678'
-- FROM (
--          SELECT id FROM ingredient
--          WHERE name IN (
--                         'Chicken Breast', 'Ground Beef', 'Tomato',
--                         'Onion', 'Garlic', 'Bell Pepper', 'Milk'
--              )
--      ) as needed_items;

select *
from meal_plan;